encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:entry_name>", views.show_entry, name="show_entry"),
    path("search/", views.search_entry, name="search_entry"),
    path("create/", views.create_entry, name="create_entry"),
    path("edit/<str:entry_name>", views.edit_entry, name="edit_entry"),
    path("random/", views.random_entry, name="random_entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import random
from markdown2 import Markdown
from django.shortcuts import render
from django import forms
from django.http import HttpResponse

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


# Renders a page that displays the contents of that encyclopedia entry
def show_entry(request, entry_name):
    entry_name = entry_name.lower()
    if util.get_entry(entry_name) is not None:
        return render(request, "encyclopedia/entry.html", {
            "entry_name": entry_name,
            "content": convert_markdown_to_html(util.get_entry(entry_name))
        })
    else:
        return render(request, "encyclopedia/error.html", {
            "message": "Sorry, no entry found for that specific term."
        })


# Handles search queries (without Django Forms)
def search_entry(request):
    if request.method == "POST":
        query = request.POST["q"].lower()
        # If no query entered
        if query == "":
            return render(request, "encyclopedia/search.html", {
            "query": query,
            "search_results": None
            })
        # If query entered, check if query is substring of an existing entry
        saved_entries = [x.lower() for x in util.list_entries()]
        matching_entries = [s for s in saved_entries if query in s]
        # If query perfectly matches an entry and it's the only entry
        if len(matching_entries) == 1 and query == matching_entries[0]:
            return render(request, "encyclopedia/entry.html", {
                "entry_name": query,
                "content": convert_markdown_to_html(util.get_entry(query))
            })
        # If query is not part of an existing entry or there are multiple possible entries
        else:
            return render(request, "encyclopedia/search.html", {
            "query": query,
            "search_results": matching_entries if len(matching_entries) >= 1 else None
            })
    return render(request, "encyclopedia/error.html", {
        "message": "Hmm, something went wrong."
    })


# Handles entry creation (with Django Forms)
def create_entry(request):
    if request.method == "POST":
        new_entry_form = NewEntryForm(request.POST)
        if new_entry_form.is_valid():
            # Check Captcha value
            captcha = int(new_entry_form.cleaned_data["captcha"])
            if captcha != 3:
                return render(request, "encyclopedia/error.html", {
                    "message": "Failed to publish new entry (wrong captcha)."
                })
            # Check entry title
            saved_entries = saved_entries = [x.lower() for x in util.list_entries()]
            entry_title = new_entry_form.cleaned_data["entry_title"].lower()
            if entry_title in saved_entries:
                return render(request, "encyclopedia/error.html", {
                    "message": "Failed to publish new entry (already exists in Wiki database)."
                })
            # Save entry to disk and redirect user to new entry's page
            entry_description = new_entry_form.cleaned_data["entry_description"]
            util.save_entry(entry_title, entry_description)
            return render(request, "encyclopedia/entry.html", {
                "entry_name": entry_title,
                "content": convert_markdown_to_html(util.get_entry(entry_title))
            })

        # If form is not valid
        else:
            return render(request, "encyclopedia/create.html", {
            "new_entry_form": NewEntryForm()
        })
    
    return render(request, "encyclopedia/create.html", {
            "new_entry_form": NewEntryForm()
        })
    

# Handles entry editing
def edit_entry(request, entry_name):
    # GET request
    if request.method == "GET":
        if entry_name is not None:
            entry_description = util.get_entry(entry_name)
            initial = {'entry_description': entry_description}
            return render(request, "encyclopedia/edit.html", {
                "entry_name": entry_name,
                "edit_form": EditForm(initial=initial)
            })
        else:
            return render(request, "encyclopedia/error.html", {
            "message": "Hmm, something went wrong."
        })
    # POST request
    else:
        edit_form = EditForm(request.POST)
        if edit_form.is_valid():
            # Check Captcha value
            captcha = int(edit_form.cleaned_data["captcha"])
            if captcha != 5:
                return render(request, "encyclopedia/error.html", {
                    "message": "Failed to edit entry (wrong captcha)."
                })
            # Process new description
            new_description = edit_form.cleaned_data["entry_description"]
            util.save_entry(entry_name, new_description)
            return render(request, "encyclopedia/entry.html", {
                "entry_name": entry_name,
                "content": convert_markdown_to_html(util.get_entry(entry_name))
            })
        # If form is not valid
        else:
            return render(request, "encyclopedia/error.html", {
                "message": "Hmm, something went wrong."
            })


# Handles returning of a random entry page
def random_entry(request):
    saved_entries = util.list_entries()
    random_int = random.randint(0, len(saved_entries) - 1)
    random_entry = saved_entries[random_int].lower()
    return render(request, "encyclopedia/entry.html", {
        "entry_name": random_entry,
        "content": convert_markdown_to_html(util.get_entry(random_entry))
    })


# Converts markdown to HTML with markdown2 library
def convert_markdown_to_html(content):
    markdowner = Markdown()
    return markdowner.convert(content)


# Class which defines new entry form content
class NewEntryForm(forms.Form):
    entry_title = forms.CharField(label="Entry title",
        min_length=1,
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder': "Enter a descriptive title"}) #replaces default widget
        )
    entry_description = forms.CharField(
        label="Description (use Markdown language)",
        min_length=1,
        max_length=14000,
        widget=forms.Textarea(attrs={'placeholder': "What do you know about this specific subject?"})) #replaces default widget
    captcha = forms.IntegerField(
        label="Captcha: How much is 5 + 5 - 7 ? ")


# Class which defines entry editing form content
class EditForm(forms.Form):
    entry_description = forms.CharField(label="Description (use Markdown language)",
        min_length=1, max_length=14000, widget=forms.Textarea)
    captcha = forms.IntegerField(label="Captcha: How much is 3 + 4 - 2 ? ")

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}Create new entry{% endblock %}

{% block body %}
    <h1>Creating a new entry</h1>
    <form action="{% url 'wiki:create_entry' %}" method="POST">
        {% csrf_token %}
        {{ new_entry_form }}
        <button type="submit" class="btn btn-dark">Publish new entry</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}Edit entry{% endblock %}

{% block body %}
    <h1>Editing "{{ entry_name|capfirst }}"</h1>
    <form action="{% url 'wiki:edit_entry' entry_name %}" method="POST">
        {% csrf_token %}
        {{ edit_form.entry_description.label_tag }}
        <code>{{ edit_form.entry_description }}</code>
        {{ edit_form.captcha.label_tag }}
        {{ edit_form.captcha }}
        <button type="submit" class="btn btn-dark">Save changes</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}{{ entry_name|capfirst }}{% endblock %}

{% block body %}
<div>
    {{ content|safe }}
</div>
<div>
   <form action="{% url 'wiki:edit_entry' entry_name %}" method="GET">
       <button type="submit" class="btn btn-dark">Edit entry</button>
   </form>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}Error{% endblock %}

{% block body %}
<h1>{{ message }}</h1>
<a href="{% url 'wiki:index' %}">Go somewhere safe</a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:show_entry' entry %}">{{ entry|capfirst }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search_entry' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" minlength="1" maxlength="30" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create_entry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search results
{% endblock %}

{% block body %}
    <h1>Search results for "{{ query }}"</h1>

    {% if search_results %}
    <ul>
        {% for result in search_results %}
            <li><a href="{% url 'wiki:show_entry' result %}">{{ result|capfirst }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No results</p>
    {% endif %}

{% endblock %}